service:
  name: retroko-shell-api
  type: webservice
  env: python-3.10
  build_command: uvicorn retroko-shell-api:app --host 0.0.0.0 --port 8000
  public_path: retroko-shell-api
  repo: https://github.com/WM-AI-TECH-IA/RETROKO.tight
