services:
  - type: web
    name: core
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn core.main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: ENV
        value: production

  - type: web
    name: shell-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn shell.main:app --host 0.0.0.0 --port 8001
    plan: free
    envVars:
      - key: ENV
        value: production
