services:
  - type: web
    name: retroko-secure-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host=0.0.0.0 --port=1000
    plan: free
    branch: main
